### ISSUE TITLE
upstream does not....

### ISSUE THREAD

**Issue by Ducasse** [astares/pharo-contributor#2]
Hi torsten

I did the following:

Gofer it     
    smalltalkhubUser: 'TorstenBergmann' project: 'Contribution';
    package: 'Contribution-Tool';
    load.
	
#CTPHelpTopic asClass open

Then I followed the help Keep own fork in sync

  
git checkout development
Switched to branch 'development'
Your branch is up-to-date with 'origin/development'.

/PharoCodeBase/pharo(development) »  git pull upstream development
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

And I do not really do what to do. I will check with my git experts.

Stef

**Comment by astares** [comment]
Use the last page of the help - there is a tool that you can invoke just with a single click

**Comment by astares** [comment]
I added two Videos to the readme to explain the tool
